trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_OPTS: "-Xmx1024m"
  azureSubscription: '2TDSPR - RM 96466 - Kaue Caponero Figueiredo'
  appName: 'bluegather-1717645418740'
  resourceGroup: 'bluegather-1717645418740-rg'
  region: 'centralus'
  pricingTier: 'F1'

steps:
- task: Maven@3
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'clean install'
    options: '-DskipTests'

- task: CopyFiles@2
  inputs:
    contents: '**/target/*.jar'
    targetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

- task: AzureWebApp@1
  inputs:
    azureSubscription: '$(azureSubscription)'
    appName: '$(appName)'
    resourceGroupName: '$(resourceGroup)'
    package: '$(Build.ArtifactStagingDirectory)/**/*.jar'
    runtimeStack: 'JAVA|17-java17'
    startupCommand: ''